<?php
	$tests = array( 1 => array(	'1. What do you say when someone is thirsty? Why don\'t you have a %blank% ?<br />',
								'2. What do you say when someone is going away? Bye! Have a good %blank% .<br />',
								'3. I like to swim. I usually go %blank% at weekends.<br />',
								'4. I\'m tired. Please, %blank% away.<br />',
								'5. Michael %blank% into his room and shut the door.<br />',
								'6. Do you like basketball? Yes, I %blank% .<br />',
								'7. Do you like doing the washing-up? No, I %blank% .<br />',
								'8. What do you %blank% to relax? I listen to music.<br />',
								'9. Did you do your homework? No, I\'m %blank% to do it now.<br />',
								'10. Did you speak to Lee today? No, I %blank% to her yesterday.<br />',
								'11. Is it easy to speak English? No,I always %blank% a lot of mistakes when I speak English.<br />',
								'12. If I %blank% my homework every day, my English will improve.<br />',
								'13. I\'m going to %blank% a big effort to speak English in Ireland.<br />',
								'14. I am %blank% an English test now.<br />',
								'15. Where do you %blank% from? I\'m from Korea.<br />',
								'16. I knocked on the door and the teacher said, " %blank% in!"<br />',
								'17. When I %blank% out, my friend was still waiting for me.<br />',
								'18. Are you going out? %blank% an umbrella. It\'s raining.<br />',
								'19. Can I %blank% a photograph here?<br />',
								'20. It %blank% me 15 minutes to get to school.<br />'),
									
					2 => array(	'1.	When she visited me yesterday, she %blank% me flowers.<br />',
								'2. I got %blank% at 6.30 this morning. I\'m tired now.<br />',
								'3. My father always turns %blank% the TV to watch the news.<br />',
								'4. Come %blank% ! We\'re late.<br />',
								'5. Our plane takes %blank% at 12.30.<br />',
								'6. What time did you go %blank% bed?<br />',
								'7. We travelled to Ireland %blank% plane.<br />',
								'8. What does a taxi man do? He %blank% a taxi.<br />',
								'9. What does a cyclist do? He %blank% a bicycle.<br />',
								'10. Cho is working in Hong Kong. She will stay there %blank% 3 years.<br />',
								'11. Last year it was 2010. It will be 2012 %blank% year.<br />',
								'12. In the past, people didn\'t have TV. In the %blank% , people may travel to Mars.<br />',
								'13. When you come to the crossroads, turn left not %blank% .<br />',
								'14. She\'s a good driver, she drives %blank% .<br />',
								'15. Her sister is a bad driver. She drives %blank% .<br />',
								'16. It is kind %blank% you to help me.<br />',
								'17. Where do I pay %blank% our meal?<br />',
								'18. This book belongs %blank% you.<br />',
								'19. Parents look %blank% their children.<br />',
								'20. I\'m looking %blank% something nice for my sister\'s birthday.<br />'),
					
					3 => array(	'1. I\'m interested %blank% hearing all your news.<br />',
								'2. He apologised %blank% being late.<br />',
								'3. He works 12 hours a day. He\'s a hard %blank% .<br />',
								'4. The students are %blank% nice clothes.<br />',
								'5. You need %blank% clothes in cold weather.<br />',
								'6. My brother is medium height. He is neither short nor %blank% .<br />',
								'7. I have a pain in my head. I have a %blank% .<br />',
								'8. She cuts hair. What\'s her job?  She\'s a %blank% .<br />',
								'9. He services cars. What\'s his job?  He\'s a %blank% .<br />',
								'10. He serves people at a table in a restaurant. What\'s his job?  He\'s a %blank% .<br />',
								'11. He makes a lot of phone %blank% .<br />',
								'12. Are you going %blank% holiday this summer?<br />',
								'13. I want to sleep in a tent, so I want to go %blank% .<br />',
								'14. I booked a room in this hotel. I have a %blank% .<br />',
								'15. The person you meet at the reception desk is the %blank% .<br />',
								'16. You can get hot food quickly in a %blank% food restaurant.<br />',
								'17. What do we call a movie where cowboys rob a train? A %blank% .<br />',
								'18. What do we call a movie with lots of songs and dancing?  A %blank% .<br />',
								'19. In most countries, there are morning newspapers and %blank% newspapers.<br />',
								'20. People talk about very personal and private things in their lives in %blank% shows.<br />'),
					
					4 => array('<p style="line-height:20px; width:600px; border:1px solid #ccc; padding:10px;">The contemporary Irish writer, <strong>Colum McCann</strong> is the author of 5 novels and 2 collections of stories. He has won numerous international literary awards. Zoli, Dancer and This Side of Brightness were international bestsellers, and his fiction has been published in over 30 languages. He was born in Dublin and now lives in New York.<br /><br />
 
This test is based on Pages 5 – 7 of Let The Great World Spin, published by Bloomsbury in 2009 and described by Dave Eggers as \'one of the greatest-ever novels about New York\'. In the test, 20 words are missing. You must find the missing word in each case.</p><p style="line-height:20px; width:600px;"><strong>(Page 5)</strong>...... Below him, a single pigeon swooped %blank% ','from the top floor of the Federal Office Building, as if anticipating the fall. The movement %blank% ','the eyes of some watchers and they followed the gray flap against the small of the standing man. The bird shot from one eave to another, and it was then the watchers %blank% ','that they had been joined by others at the windows of %blank%, ','where blinds were being lifted and a few glass panes labored upward. All that could be seen was a pair of elbows or the end of a shirtsleeve, or an arm garter, but then it was joined by a head, or an odd-looking pair of hands above it, lifting the frame even higher. In the windows of nearby %blank%, ','figures came to look out – men in shirtsleeves and women in bright blouses, wavering in the glass like funhouse apparitions.</p>

<p style="line-height:20px; width:600px;">Higher still, a weather helicopter executed a dipping turn over the Hudson – a curtsy to the fact that the summer day was going to be cloudy and cool anyway – and the rotors beat a %blank% ','over the warehouses of the West Side. At first the helicopter looked lopsided in its advance, and a small side window was slid open as if the machine were looking for air. A lens appeared in the open window. It caught a brief flash of light. After a moment the helicopter corrected beautifully and spun across the expanse.</p>

<p style="line-height:20px; width:600px;">Some cops on the West Side Highway switched on their misery lights, swerved fast off the exit ramps, making the morning all the more magnetic.</p>

<p style="line-height:20px; width:600px;">A charge entered the air all around the watchers and - now that the day had been made official by sirens – there was a chatter among them, their balance set on edge, their calm fading, and they turned to one another and began to %blank%, ','would he jump, would he fall, would he tiptoe along the ledge, did he work there, was he solitary, was he a decoy, was he wearing a uniform, did anyone have binoculars? Perfect strangers touched one another on the %blank%. ','Swearwords went between them, and whispers that there\'d been a botched robbery, that he was some sort of cat burglar, that he\'d taken hostages, he was an Arab, a Jew, a Cypriot, an IRA man, that he was really just a %blank% ','stunt, a corporate scam, Drink more Coca-Cola, Eat more Fritos, Smoke more Parliaments, Spray more Lysol, Love more Jesus. Or that he was a protester and he was going to <strong>(Page 6)</strong> hang a slogan, he would slide it from the towerledge, leave it there to flutter in the breeze, like some giant piece of sky laundry – NIXON OUT NOW! REMEMBER \'NAM, SAM! INDEPENDENCE FOR INDOCHINA!- and then someone said that maybe he was hang glider or a parachutist, and all the others laughed, but they were perplexed by the cable at his feet, and the rumors began again, a collision of curse and whisper, augmented by an increase in sirens, which got their hearts pumping even more, and the helicopter found a purchase near the west side of the towers, while down in the foyer of the World %blank% ','Center the cops were sprinting across the marble floor, and the undercovers were whipping out badges from beneath their shirts, and the fire trucks were pulling into the plaza, and the redblue dazzled the glass, and a flatbed truck arrived with a cherry picker, its fat wheels bouncing over the curb, and someone laughed as the picker kiltered sideways, the driver looking up, as if the basket might reach all that sad huge way, and the security guards were shouting into their walkie-talkies, and the whole August morning was blown wide open, and the watchers stood rooted, there was no going %blank% ','for a while, the voices rose to a crescendo, all sorts of accents, a babel, until a small red-headed man in the Home Title Guarantee Company on Church Street lifted the sash of his office window, placed his elbows on the sill, took a deep breath, leaned out, and roared into the distance: Do it, asshole!</p>

<p style="line-height:20px; width:600px;">There was a dip before the laughter, a second before it sank in among the watchers, a reverence for the man\'s irreverence, because %blank% ','that\'s what so many of them felt – Do it, for chrissake! Do it! – and then a torrent of chatter was released, a call-and-response, and it seemed to %blank% ','all the way from the windowsill down to the sidewalk and along the cracked pavement to the corner of Fulton, down the block along Broadway, where it zigzagged down John, hooked around to Nassau, and went on, a domino line of laughter, but with an edge to it, a longing, an awe, and many of the watchers realized with a %blank% ','that no matter what they said, they really wanted to witness a great fall, see someone arc downward all that distance, to disappear from the sight line, flail, smash to the ground, and give the Wednesday an electricity, a meaning, that all they needed to become a family was one millisecond of slippage, while the others – those who wanted him to stay, to hold the line, to become the brink, but no farther – felt viable now with disgust for the shouters: they wanted the man to %blank% ','himself, step backward into the arms of the cops instead of the sky.</p>

<p style="line-height:20px; width:600px;"><strong>(Page 7)</strong>"They were jazzed now. Pumped. The lines were drawn. Do it, asshole! Don\'t do it!"</p>

<p style="line-height:20px; width:600px;">Way above there was a movement. In the dark clothing his every twitch counted. He folded over, a half-thing, bent, as if examining his shoes, like a pencil mark, most of which had been erased. The posture of a diver. And then saw it. The watchers stood, silent. Even those who had wanted the man to jump felt the air knocked out. They drew back and moaned.</p>

<p style="line-height:20px; width:600px;">A body was sailing out into the middle of the air.</p>

<p style="line-height:20px; width:600px;">He was gone. He\'d done it. Some blessed themselves. Closed their eyes. Waited for the thump. The body twirled and cought and flipped, thrown around by the wind.</p>

<p style="line-height:20px; width:600px;">Then a shout sounded across the watchers, a woman\'s voice: God, oh God, it\'s a shirt, it\'s just a shirt.</p>

<p style="line-height:20px; width:600px;">It was falling, falling, falling, yes a sweatshirt, fluttering, and then their eyes left the clothing in midair, because high above the man had unfolded upward from his crouch, and a new hush settled over the cops above and the watchers below, a rush of %blank% ','rippling among them, because the man had arisen from the bend holding a long thin bar in his hands, jiggling it, testing its weight, bobbing it up and down in the air, a long black bar, so pliable that the ends swayed, and his gaze was fixed on the far %blank%, ','still wrapped in scaffolding, like a wounded thing waiting to be reached, and now the %blank% ','at his feet made sense to everyone, and whatever else it was there would be no chance they could pull away now, no morning %blank%, ','no conference room cigarette, no nonchalant carpet shuffle; the waiting had been made magical, and they %blank% as he lifted one dark-slippered foot, like a man about to enter warm gray water.</p>

<p style="line-height:20px; width:600px;">The watchers below pulled in their breath all at once. The air felt suddenly shared. The man above was a word they seemed to know, though they had not heard it before.</p><p style="line-height:20px; width:600px;">Out he went.</p>

'),
					5 => array(	'1. Is that your bag? %blank% , it is.<br />',
								'2. How are you? Very %blank% , thank you.<br />',
								'3. Fernando and I %blank% good friends.<br />',
								'4. What time %blank% it?<br>',
								'5. There is a letter %blank% you.<br />',
								'6. I cannot find %blank% key.<br />',
								'7. I cannot find %blank% key to my apartment.<br />',
								'8. I am waiting %blank% my friend.<br />',
								'9. Would you like %blank% cup of tea?<br />',
								'10. Are you able %blank% speak Chinese?<br />',
								'11. This is a photo of %blank% sister.<br />',
								'12. How %blank% is it from Dublin to Cork?<br />',
								'13. How %blank% does it cost to go by train from Dublin to Cork?<br />',
								'14. I don`t have enough %blank% to pay for the ticket.<br />',
								'15. I would really %blank% to go there.<br />',
								'16. The language of Saudi Arabia is %blank% <br />',
								'17. The language of Brazil is %blank% <br />',
								'18. The language of Venezuela is %blank% <br />',
								'19. How many languages do you %blank% ?<br />',
								'20. Not as many %blank% I would like.<br />'),
					
					6 => array(	'1. There are stars in %blank% sky.<br />',
								'2. Do you know the names %blank% the stars?<br />',
								'3. Yes, I know some of %blank% .<br />',
								'4. The Irish writer, Sean O`Casey wrote `The Plough and the %blank% `.<br>',
								'5. What %blank% you doing now?<br />',
								'6. I am looking %blank% my dictionary.<br />',
								'7. My sister %blank% doing her homework now.<br />',
								'8. Where is your sister? She is %blank% the kitchen.<br />',
								'9. Where %blank% you now?<br />',
								'10. I am %blank% home.<br />',
								'11. When are you coming out %blank% play?<br />',
								'12. I am sorry. I have %blank% time.<br />',
								'13. You should take %blank% break.<br />',
								'14. I know,  %blank% I have to finish my homework.<br />',
								'15. You always work %blank% hard.<br />',
								'16. Yes, that is %blank% I am not as clever as you.<br />',
								'17. Nonsense! You are much more clever than %blank% . <br />',
								'18. OK. I will be out in half an %blank% .<br />',
								'19. Great! We can go to meet %blank% friends.<br />',
								'20. Good idea! Let`s %blank% that.<br />'),
					
					7 => array(	'1. He`s a construction worker. He works on a construction %blank% (<strong><i> site/seat </i></strong>).<br />',
								'2. He`s a teacher. He works in a %blank% (<strong><i> factory/school </i></strong>).<br />',
								'3. He`s an oil worker. He works on an oil %blank% (<strong><i> rag/rig </i></strong>).<br />',
								'4. She`s a programmer. She works on %blank% (<strong><i> computers/desks </i></strong>).<br>',
								'5. He works on engines. He`s an %blank% (<strong><i> engineer/entertainer </i></strong>)<br />',
								'6. He takes photos. He`s a %blank% (<strong><i> writer/photographer </i></strong>).<br />',
								'7. He designs buildings. He`s an %blank% (<strong><i> architect/artist </i></strong>).<br />',
								'8. She works in a hospital. She`s a %blank% (<strong><i> policewoman/nurse </i></strong>).<br />',
								'9. He`s a barman. He works in a %blank% (<strong><i> pub/shop </i></strong>).<br />',
								'10. She`s a personal assistant. She works in an %blank% (<strong><i> elevator/office </i></strong>).<br />',
								'11. The people who buy your products are your %blank% (<strong><i> friends/customers </i></strong>).<br />',
								'12. The people you work with are your %blank% (<strong><i> colleagues/neighbours </i></strong>).<br />',
								'13. If you only work 20 hours a week, you work %blank% (<strong><i> full-time/part-time </i></strong>).<br />',
								'14. An agreement to work for a company is a %blank% (<strong><i> conflict/contract </i></strong>).<br>',
								'15. If you work for a company, you are an %blank% (<strong><i> employee/entrepreneur </i></strong>).<br />',
								'16. My job finishes next week. It is %blank% (<strong><i> temporary/permanent </i></strong>).<br />',
								'17. If you work extra hours, you do %blank% (<strong><i> full-time/overtime </i></strong>).<br />',
								'18. The person who runs the whole company is the company %blank% (<strong><i> secretary/chief executive </i></strong>).<br />',
								'19. The person who is in charge of making the products is the %blank% (<strong><i> finance director/production director </i></strong>).<br />',
								'20. The person who is in charge of the money in the company is the %blank% (<strong><i> finance director/sales director </i></strong>).<br />'),
					
					
					
								
					8 => array(	'1. Maria has people skills. She`s a good %blank% (<strong><i> listener/presenter </i></strong>).<br />',
								'2. John is good with figures. He has %blank% (<strong><i> problem-solving/language </i></strong>) skills.<br />',
								'3. Warehouse workers are %blank% (<strong><i> skilled/unskilled </i></strong>) workers.<br />',
								'4. Store managers are %blank% (<strong><i> skilled/unskilled </i></strong>) workers.<br>',
								'5. I usually %blank% (<strong><i> spend/lose </i></strong>) 30 minutes every morning checking my e-mail.<br />',
								'6. I %blank% (<strong><i> wasted/saved </i></strong>) 2 weeks waiting for a reply to my letter.<br />',
								'7. I used more time than I had planned for that job, so I %blank% (<strong><i> lost/wasted </i></strong>) time.<br />',
								'8. I %blank% (<strong><i> saved/used </i></strong>) 2 hours by getting a direct flight to Hong Kong.<br />',
								'9. Do you have time to meet on Monday? Yes, I`m %blank% (<strong><i> busy/free </i></strong>).<br />',
								'10. Where shall we meet? Let`s meet %blank% (<strong><i> at/to </i></strong>) my office.<br />',
								'11. When shall we meet? How %blank% (<strong><i> on/about </i></strong>) 12.30?<br />',
								'12. What do you do in your free time? %blank% (<strong><i> I play golf/I work </i></strong>) .<br />',
								'13. I don`t like to stay at home for my holidays. I go %blank% (<strong><i> abroad/nowhere </i></strong>).<br />',
								'14. A million is %blank% (<strong><i> more/less </i></strong>) than a billion.<br>',
								'15. Ten thousand = %blank% (<strong><i> 100,000/10,000 </i></strong>).<br />',
								'16. VAT is %blank% (<strong><i> added to/subtracted from </i></strong>) the basic price of an article.<br />',
								'17. The %blank% (<strong><i> exchange/currency </i></strong>) of Ireland is the Euro.<br />',
								'18. I can`t afford that. It is too %blank% (<strong><i> cheap/expensive </i></strong>).<br />',
								'19. John saves his money. He is %blank% (<strong><i> careless/careful </i></strong>) with money.<br />',
								'20. Jim wastes his money. He buys things he %blank% (<strong><i> needs/doesn`t need </i></strong>).<br />'),
					
		
								
					
					9 => array(	'1. The bank is giving me a mortgage. I`m %blank% (<strong><i> renting/buying </i></strong>) my house.<br />',
								'2. I %blank% (<strong><i> own/owe </i></strong>) money to the bank.<br />',
								'3. The bank sends me a statement every month, showing me the %blank% (<strong><i> balance/equivalence </i></strong>)of my account.<br />',
								'4. The hotel I work for is a %blank% (<strong><i> service/production </i></strong>) company.<br>',
								'5. The DVDs we sell are %blank% (<strong><i> distributed/manufactured </i></strong>) in China.<br />',

								'6. These products are %blank% (<strong><i> driven/shipped </i></strong>) from China to many countries.<br />',
								'7. A convenience store is a small shop that is open %blank% (<strong><i> long/daytime </i></strong>) hours.<br />',
								'8. E-commerce involves %blank% (<strong><i> department store/internet shopping </i></strong>).<br />',
								'9. I have a problem with my DVD player. It has broken %blank% (<strong><i> up/down </i></strong>) .<br />',
								'10. This is the service department. Does your DVD player have a %blank% (<strong><i> guarantee/agreement </i></strong>)?<br />',
								'11. My boss is on another call. Can I %blank% (<strong><i> take/hear </i></strong>) a message?<br />',
								'12. Yes. Can I leave a message? It`s very %blank% (<strong><i> urgent/unimportant </i></strong>) .<br />',
								'13. I`m late. Would it be possible to %blank% (<strong><i> postpone/arrange </i></strong>) the meeting?<br />',
								'14. I look forward to %blank% (<strong><i> meeting/hearing </i></strong>) from you.<br>',
								'15. Can you %blank% (<strong><i> delete/forward </i></strong>) my e-mail to your boss.<br />',
								'16. The documents he requested are in the %blank% (<strong><i> detachment/attachment </i></strong>).<br />',
								'17. Before making a presentation, you need to check the %blank% (<strong><i> injector/projector </i></strong>).<br />',
								'18. If you have any questions, please, feel free to %blank% (<strong><i> intercede/interrupt </i></strong>) me.<br />',
								'19. People who make business presentations usually work in the %blank% (<strong><i> production/sales </i></strong>) department of a company.<br />',
								'20. A %blank% (<strong><i> tie/pie </i></strong>) chart is a clear way to show a company`s sales in percentages around the world.<br />'),
					
					
					10 => array(	'1. A site %blank% (<strong><i> trip/tour </i></strong>) involves being shown around the company site.<br />',
								'2. This company does not %blank% (<strong><i> allow/give </i></strong>) photography during a visit to the site.<br />',
								'3. The research and development department is a %blank% (<strong><i> restricted/retained </i></strong>) area.<br />',
								'4. The factory is where we make the %blank% (<strong><i> research/products </i></strong>).<br>',
								'5. The R&D department is where we %blank% (<strong><i> make/design </i></strong>) new computers.<br />',
								'6. The offices are where our %blank% (<strong><i> receptionists/managers </i></strong>) work.<br />',
								'7. In a business meeting, the chairman %blank% (<strong><i> organizes/chairs </i></strong>) the meeting.<br />',
								'8. The agenda is the list of %blank% (<strong><i> items/products </i></strong>) to talk about at a meeting.<br />',
								'9. If you cannot attend a meeting, you send your %blank% (<strong><i> excuses/apologies </i></strong>) to the secretary.<br />',
								'10. The minutes of the meeting are the %blank% (<strong><i> time/notes </i></strong>) of what is said and decided in the meeting.<br />',
								'11. At the beginning of the next meeting, people agree that the minutes are %blank% (<strong><i> written/correct </i></strong>).<br />',
								'12. At the beginning of the meeting, the chairman %blank% (<strong><i> arranges/opens </i></strong>) the meeting.<br />',
								'13. When closing the meeting, the chairman sums %blank% (<strong><i> up/down </i></strong>) the main ideas.<br />',
								'14. During the meeting, the secretary %blank% (<strong><i> takes/repeats </i></strong>) the minutes.<br>',
								'15. After the meeting, the secretary sends %blank% (<strong><i> forward/out </i></strong>) the minutes.<br />',
								'16. The person who keeps and checks the financial records of a company is the %blank% (<strong><i> CEO/Accountant </i></strong>).<br />',
								'17. The person who supplies information about a company to the public is the %blank% (<strong><i> PR officer/PA </i></strong>).<br />',
								'18. The person who studies business operations and uses a computer to plan changes is the %blank% (<strong><i> computer programmer/systems analyst </i></strong>).<br />',
								'19. A person or company that sells a particular type of product to a customer is a %blank% (<strong><i> supplier/retailer </i></strong>).<br />',
								'20. A person or company that sells goods in large quantities to businesses is a %blank% (<strong><i> retailer/wholesaler </i></strong>).<br />'),
								
								
					
					
					
					11 => array(	'1. A document sent by a seller to a customer that lists the goods sold and says how much they cost is an %blank% (<strong><i> invoice/order </i></strong>).<br />',
								'2. The value of the goods or services sold during a certain period of time is %blank% (<strong><i> income/turnover </i></strong>).<br />',
								'3. The company did not make a profit. It just broke %blank% (<strong><i> up/even </i></strong>).<br />',
								'4. The company has taken out a %blank% (<strong><i> loan/deposit </i></strong>) to build up its business.<br>',
								'5. The percentage of sales a company or a product has is its market %blank% (<strong><i> plan/share </i></strong>).<br />',
								'6. The %blank% (<strong><i> life cycle/range </i></strong>) of a product is the time people continue to buy it.<br />',
								'7. Good marketing should increase the volume of %blank% (<strong><i> inquiries/sales </i></strong>).<br />',
								'8. A company`s sales target is how much it wants to %blank% (<strong><i> measure/sell </i></strong>) in a certain period of time.<br />',
								'9. An advertising agency %blank% (<strong><i> advises/consults </i></strong>) companies on advertising.<br />',
								'10. Sales %blank% (<strong><i> product/figures </i></strong>) show how much a company has sold over a certain time.<br />',
								'11. Production %blank% (<strong><i> costs/orders </i></strong>) are what a company must spend on production.<br />',
								'12. A company needs to %blank% (<strong><i> estimate/activate </i></strong>) the value of something.<br />',
								'13. A company needs to forecast %blank% (<strong><i> sales/a schedule </i></strong>).<br />',
								'14. A company needs to %blank% (<strong><i> prepare/call </i></strong>) a budget.<br>',
								'15. A company needs to %blank% (<strong><i> implement/invalidate </i></strong>) a plan.<br />',
								'16. In countries where the %blank% (<strong><i> employment/unemployment </i></strong>) rate is high, young people tend to study more.<br />',
								'17. When the value of a country`s exports is greater than the value of its imports, we say that the %blank% (<strong><i> level/balance </i></strong>) of trade is favourable.<br />',
								'18. Prices increased again last month, so the %blank% (<strong><i> inflation/deflation </i></strong>) rate rose to 5%.<br />',
								'19. Less government bureaucracy will encourage %blank% (<strong><i> foreign/declining </i></strong>) investment.<br />',
								'20. The goverment is offering attractive tax %blank% (<strong><i> incentives/increases </i></strong>) to encourage new business.<br />'),
					
					
					
					
					
					);
	
	$anwsers = array(	1 => array(	1 => array('DRINK'),
									2 => array('JOURNEY'),
									3 => array('SWIMMING'),
									4 => array('GO'),
									5 => array('WENT'),
									6 => array('DO'),
									7 => array("don't",'don`t'),
									8 => array('DO'),
									9 => array('GOING'),
									10=> array('SPOKE'),
									11=> array('MAKE'),
									12=> array('DO'),
									13=> array('MAKE'),
									14=> array('DOING'),
									15=> array('COME'),
									16=> array('COME'),
									17=> array('CAME'),
									18=> array('TAKE'),
									19=> array('TAKE'),
									20=> array('TAKES')),
									
						2 => array(	1 => array('BROUGHT'),
									2 => array('UP'),
									3 => array('ON'),
									4 => array('ON'),
									5 => array('OFF'),
									6 => array('TO'),
									7 => array('BY'),
									8 => array('DRIVES'),
									9 => array('RIDES'),
									10=> array('FOR'),
									11=> array('NEXT'),
									12=> array('FUTURE'),
									13=> array('RIGHT'),
									14=> array('WELL'),
									15=> array('BADLY'),
									16=> array('OF'),
									17=> array('FOR'),
									18=> array('TO'),
									19=> array('AFTER'),
									20=> array('FOR')),
						
						3 => array(	1 => array('IN'),
									2 => array('FOR'),
									3 => array('WORKER'),
									4 => array('WEARING'),
									5 => array('WARM'),
									6 => array('TALL'),
									7 => array('HEADACHE'),
									8 => array('HAIRDRESSER'),
									9 => array('MECHANIC'),
									10=> array('WAITER'),
									11=> array('CALL'),
									12=> array('ON'),
									13=> array('CAMPING'),
									14=> array('RESERVATION'),
									15=> array('RECEPTIONIST'),
									16=> array('FAST'),
									17=> array('WESTERN'),
									18=> array('MUSICAL'),
									19=> array('EVENING'),
									20=> array('TALK')),
						
						4 => array(	1 => array('DOWN'),
									2 => array('CAUGHT'),
									3 => array('NOTICED'),
									4 => array('OFFICES'),
									5 => array('SKYSCRAPERS'),
									6 => array('RHYTHM'),
									7 => array('SPECULATE'),
									8 => array('ELBOWS'),
									9 => array('PUBLICITY'),
									10=> array('TRADE'),
									11=> array('ANYWHERE'),
									12=> array('SECRETLY'),
									13=> array('RIPPLE'),
									14=> array('SHIVER'),
									15=> array('SAVE'),
									16=> array('EMOTION'),
									17=> array('TOWER'),
									18=> array('CABLE'),
									19=> array('COFFEE'),
									20=> array('WATCHED')),
							
						5 => array(	1 => array('YES'),
									2 => array('WELL'),
									3 => array('ARE'),
									4 => array('IS'),
									5 => array('FOR'),
									6 => array('MY'),
									7 => array('THE'),
									8 => array('FOR'),
									9 => array('A'),
									10=> array('TO'),
									11=> array('MY'),
									12=> array('FAR'),
									13=> array('MUCH'),
									14=> array('MONEY'),
									15=> array('LIKE'),
									16=> array('ARABIC'),
									17=> array('PORTUGUESE'),
									18=> array('SPANISH'),
									19=> array('SPEAK'),
									20=> array('AS')),
									
						6 => array(	1 => array('THE'),
									2 => array('OF'),
									3 => array('THEM'),
									4 => array('STARS'),
									5 => array('ARE'),
									6 => array('UP'),
									7 => array('IS'),
									8 => array('IN'),
									9 => array('ARE'),
									10=> array('AT'),
									11=> array('TO'),
									12=> array('NO'),
									13=> array('A'),
									14=> array('BUT'),
									15=> array('TOO'),
									16=> array('BECAUSE'),
									17=> array('I'),
									18=> array('HOUR'),
									19=> array('OUR'),
									20=> array('DO')),
									
						7 => array(	1 => array('SITE'),
									2 => array('SCHOOL'),
									3 => array('RIG'),
									4 => array('COMPUTERS'),
									5 => array('ENGINEER'),
									6 => array('PHOTOGRAPHER'),
									7 => array('ARCHITECT'),
									8 => array('NURSE'),
									9 => array('PUB'),
									10=> array('OFFICE'),
									11=> array('CUSTOMERS'),
									12=> array('COLLEAGUES'),
									13=> array('PART-TIME'),
									14=> array('CONTRACT'),
									15=> array('EMPLOYEE'),
									16=> array('TEMPORARY'),
									17=> array('OVERTIME'),
									18=> array('CHIEFEXECUTIVE'),
									19=> array('PRODUCTIONDIRECTOR'),
									20=> array('FINANCEDIRECTOR')),
						
						8 => array(	1 => array('LISTENER'),
									2 => array('PROBLEM-SOLVING'),
									3 => array('unskilled'),
									4 => array('skilled'),
									5 => array('spend'),
									6 => array('wasted'),
									7 => array('LOST'),
									8 => array('SAVED'),
									9 => array('FREE'),
									10=> array('AT'),
									11=> array('ABOUT'),
									12=> array('IPLAYGOLF'),
									13=> array('ABROAD'),
									14=> array('LESS'),
									15=> array('10,000'),
									16=> array('ADDEDTO'),
									17=> array('CURRENCY'),
									18=> array('EXPENSIVE'),
									19=> array('CAREFUL'),
									20=> array('DOESN\'TNEED','DOESN`TNEED')),
									
						9 => array(	1 => array('buying'),
									2 => array('owe'),
									3 => array('balance'),
									4 => array('service'),
									5 => array('manufactured'),
									6 => array('shipped'),
									7 => array('long'),
									8 => array('internetshopping'),
									9 => array('down'),
									10=> array('guarantee'),
									11=> array('take'),
									12=> array('urgent'),
									13=> array('postpone'),
									14=> array('hearing'),
									15=> array('forward'),
									16=> array('attachment'),
									17=> array('projector'),
									18=> array('interrupt'),
									19=> array('sales'),
									20=> array('pie')),
						
						10 => array(1 => array('tour'),
									2 => array('allow'),
									3 => array('restricted'),
									4 => array('products'),
									5 => array('design'),
									6 => array('managers'),
									7 => array('chairs'),
									8 => array('items'),
									9 => array('apologies'),
									10=> array('notes'),
									11=> array('correct'),
									12=> array('opens'),
									13=> array('up'),
									14=> array('takes'),
									15=> array('out'),
									16=> array('Accountant'),
									17=> array('PRofficer'),
									18=> array('systemsanalyst'),
									19=> array('retailer'),
									20=> array('wholesaler')),
									
						11 => array(1 => array('invoice'),
									2 => array('turnover'),
									3 => array('even'),
									4 => array('loan'),
									5 => array('share'),
									6 => array('lifecycle'),
									7 => array('sales'),
									8 => array('sell'),
									9 => array('advises'),
									10=> array('figures'),
									11=> array('cost'),
									12=> array('estimate'),
									13=> array('sales'),
									14=> array('prepare'),
									15=> array('implement'),
									16=> array('unemployment'),
									17=> array('balance'),
									18=> array('inflation'),
									19=> array('foreign'),
									20=> array('incentives'))
						);

?>